// EIC Interview Trainer - Official Data
const EXAMS = [
  {
    id: "2026-17",
    year: 2026,
    type: "OFFICIAL",
    track: "글로벌인재",
    department: "동아시아국제학부, 글로벌엘리트학부",
    card: "문항카드 17",
    title: "Prosperity Paradox (번영의 역설)",
    category: "논리적 사고력 1",
    prepMinutes: 1,
    answerMinutes: 2,
    topic: "Prosperity Paradox – Economic success vs. life satisfaction",
    keyConflict: "경제 성장/성공이 반드시 높은 삶의 만족도로 이어지지 않는 현상",
    passage: `The \"prosperity paradox\" refers to the observation that economic growth and rising material wealth do not always lead to corresponding increases in people's life satisfaction or happiness. While countries that have experienced rapid economic development often show higher average incomes, surveys of subjective well-being sometimes reveal stagnation or even decline in reported happiness levels after a certain threshold.\n\nResearchers point to several possible explanations. One is that once basic needs are met, relative income and social comparison become more important than absolute income. Another is that the costs of economic growth—such as longer working hours, environmental degradation, weakened community ties, and increased inequality—can offset the benefits of higher material standards. Additionally, adaptation and rising expectations may cause people to quickly adjust to higher living standards, so that the initial boost in satisfaction fades over time.\n\nThis paradox raises important questions for policymakers: Should the primary goal of public policy remain maximizing GDP and economic growth, or should greater emphasis be placed on measures of well-being, work-life balance, social capital, and environmental sustainability?`,
    questions: [
      "1-1. According to the passage, what is the prosperity paradox? Explain the difference between economic success and life satisfaction, and provide two possible reasons for this difference.",
      "1-2. In your opinion, should the primary goal of government policy be economic growth or improving citizens' life satisfaction? Choose one position and support your answer with reasons and examples."
    ],
    intention: "영문 제시문을 정확히 이해하고, 경제 성장과 삶의 만족도 사이의 관계를 논리적으로 분석하며, 정책적 관점에서 자신의 입장을 근거와 함께 제시할 수 있는지 평가",
    subjects: ["영어", "사회", "통합사회"],
    keyConcepts: ["prosperity paradox", "subjective well-being", "relative income", "adaptation", "GDP vs well-being"],
    rubric: {
      high: "제시문의 핵심(번영의 역설)을 정확히 파악하고, 경제 성공과 삶의 만족도 차이를 명확히 설명. 두 가지 이상 타당한 이유 제시. 정책 목표에 대한 입장이 분명하고, 구체적인 근거와 사례로 뒷받침. 반대 관점을 인정하면서도 자신의 주장을 논리적으로 유지. 영어 표현이 자연스럽고 논리적 연결이 매끄러움.",
      mid: "제시문 내용을 대체로 이해했으나 일부 핵심이 부족. 이유나 사례가 일반적이거나 구체성이 떨어짐. 입장은 있으나 논리적 깊이가 다소 부족.",
      low: "제시문 핵심을 잘못 이해하거나 단순히 내용을 반복. 이유와 사례가 없거나 비논리적. 입장이 불분명하거나 영어 표현이 매우 제한적."
    },
    exampleCore: "상위권 답변은 ① 제시문 핵심을 한 문장으로 요약 ② 상대소득·적응·사회비용 등 구체적 이유 제시 ③ 정책 선택 시 GDP 한계와 웰빙 지표의 필요성을 사례로 연결 ④ 반대 입장(성장 우선의 필요성)을 인정한 뒤 재주장하는 구조를 갖춤.",
    coachTip: "답변 구조 추천: (1) 제시문 한 줄 요약 → (2) 차이점 + 이유 2개 → (3) 내 입장 명확히 → (4) 이유 + 구체 사례 → (5) 반대 인정 후 결론. 시간을 1분 준비 / 2분 답변으로 맞춰 연습하세요.",
    selfCheck: [
      "제시문의 핵심 개념(prosperity paradox)을 정확히 말했는가?",
      "경제 성공과 삶의 만족도 차이를 분명히 구분했는가?",
      "타당한 이유 2가지 이상을 제시했는가?",
      "정책 목표에 대한 내 입장이 명확한가?",
      "구체적 사례나 근거를 들었는가?",
      "반대 입장을 인정한 뒤 재주장했는가?",
      "영어가 비교적 자연스럽고 논리적으로 연결되는가?"
    ],
    vocab: ["prosperity", "paradox", "subjective well-being", "stagnation", "threshold", "relative income", "adaptation", "offset", "sustainability", "social capital"]
  },
  {
    id: "2026-18",
    year: 2026,
    type: "OFFICIAL",
    track: "글로벌인재",
    department: "동아시아국제학부, 글로벌엘리트학부",
    card: "문항카드 18",
    title: "AI Companion Apps",
    category: "논리적 사고력 2",
    prepMinutes: 1,
    answerMinutes: 2,
    topic: "AI Companion Apps – Benefits, risks, and regulation for adolescents",
    keyConflict: "청소년의 AI 동반자 앱 사용에 대한 규제 필요성 vs 자율성과 효용",
    passage: `Passage A\nArtificial intelligence companion applications have become increasingly popular, especially among young people. These apps use advanced language models to engage in conversations that can feel empathetic, supportive, and personalized. Users report that AI companions help reduce loneliness, provide a non-judgmental space to express emotions, and offer practical advice or motivation.\n\nPassage B\nCritics warn that heavy reliance on AI companions may hinder the development of real-world social skills. Adolescents in particular are still forming their identities and learning how to navigate complex human relationships. Substituting human interaction with AI may lead to emotional dependency, distorted expectations of relationships, and reduced ability to handle conflict or ambiguity that naturally occur with real people.\n\nPassage C\nSome researchers and policymakers argue for age-appropriate regulation. Suggestions include limiting usage time for minors, requiring transparency about the AI nature of the companion, prohibiting certain emotional manipulation techniques, and ensuring that sensitive conversations are not used for commercial data collection. Others contend that over-regulation could stifle innovation and deny young people potentially beneficial tools for mental health support.`,
    questions: [
      "2-1. Summarize the main idea of each passage (A, B, and C). Based on passages B and C, what concerns and regulatory approaches are raised regarding AI companion apps?",
      "2-2. Do you think governments should regulate AI companion apps for adolescents? State your opinion and support it with reasons and examples."
    ],
    intention: "복수의 영문 제시문을 비교·요약하고, AI 기술의 사회적 영향과 청소년 보호 사이의 균형을 논리적으로 판단할 수 있는지 평가",
    subjects: ["영어", "사회", "기술"],
    keyConcepts: ["AI companion", "loneliness", "emotional dependency", "social skills", "regulation", "transparency", "mental health"],
    rubric: {
      high: "각 제시문의 핵심을 정확하게 요약. B와 C의 우려와 규제 방안을 명확히 연결. 규제 여부에 대한 입장이 분명하고, 청소년 발달·프라이버시·기술 효용 등을 균형 있게 고려한 근거와 사례 제시. 반대 의견을 인정하면서 자신의 주장을 강화. 영어 표현과 논리 전개가 우수.",
      mid: "요약은 대체로 맞으나 세부 누락. 입장은 있으나 근거나 사례가 일반적. 균형적 시각이 다소 부족.",
      low: "제시문 내용을 혼동하거나 단순 반복. 입장이 불분명하고 근거가 약함. 영어 표현이 매우 제한적."
    },
    exampleCore: "상위권은 ① A(효용)·B(위험)·C(규제논의)를 한 문장씩 정리 ② B의 사회적 기술 저하·의존성, C의 시간제한·투명성·데이터 보호를 연결 ③ 규제 찬성/반대 입장을 명확히 한 뒤 구체 사례로 뒷받침 ④ 반대 입장을 짧게 인정 후 결론.",
    coachTip: "2-1은 '요약 → 연결'이 핵심. 2-2는 입장을 먼저 밝히고, 이유 2개 + 사례 1개를 준비한 뒤, 반대 입장을 한 문장으로 인정하세요.",
    selfCheck: [
      "A, B, C 각 제시문의 핵심을 구분해서 요약했는가?",
      "B와 C의 우려/규제 방안을 제대로 연결했는가?",
      "규제에 대한 내 입장이 명확한가?",
      "이유와 구체적 사례를 제시했는가?",
      "반대 입장을 인정한 부분이 있는가?",
      "청소년이라는 특수성을 고려했는가?",
      "영어 표현이 논리적으로 연결되는가?"
    ],
    vocab: ["companion", "empathetic", "loneliness", "dependency", "ambiguity", "regulation", "transparency", "manipulation", "stifle", "adolescent"]
  },
  {
    id: "2025-logic",
    year: 2025,
    type: "OFFICIAL",
    track: "글로벌인재",
    department: "동아시아국제학부 등 국제계열",
    card: "논리적 사고력 (영문)",
    title: "2025 논리적 사고력 (영문 제시문)",
    category: "논리적 사고력",
    prepMinutes: 1,
    answerMinutes: 2,
    topic: "2025학년도 국제계열 논리적 사고력 문항",
    keyConflict: "PDF 부록 문항카드 상세 내용 추가 예정",
    passage: "※ 이 문항의 영문 제시문 전문은 PDF 부록에서 추가 추출 후 업데이트됩니다.\n현재는 구조와 학습 흐름을 먼저 제공합니다.",
    questions: ["제시문을 읽고 핵심 쟁점에 대해 논리적으로 답하시오."],
    intention: "영문 제시문 이해 및 논리적 사고력 평가",
    subjects: ["영어", "사회"],
    keyConcepts: [],
    rubric: { high: "제시문 핵심 파악 + 명확한 입장 + 근거와 사례 + 반대 인정", mid: "대체로 이해했으나 깊이나 구체성 부족", low: "핵심 파악 미흡, 근거 부족" },
    exampleCore: "상위권 특징: 구조화된 답변, 구체 사례, 균형 잡힌 시각",
    coachTip: "6단계 프레임으로 먼저 한국어 논리를 잡은 뒤 영어로 옮기세요.",
    selfCheck: ["핵심을 파악했는가?", "입장이 명확한가?", "근거와 사례가 있는가?", "반대 입장을 고려했는가?"],
    vocab: []
  },
  {
    id: "2024-14",
    year: 2024,
    type: "OFFICIAL",
    track: "글로벌인재 / 학교생활우수자",
    department: "국제계열",
    card: "문항카드 14",
    title: "2024 인성 및 가치관 (영문)",
    category: "인성 및 가치관",
    prepMinutes: 1,
    answerMinutes: 2,
    topic: "2024학년도 인성 및 가치관 영문 제시문",
    keyConflict: "PDF 부록 상세 추출 예정",
    passage: "※ 영문 제시문 전문은 PDF 부록 문항카드에서 추가 추출 후 업데이트됩니다.",
    questions: ["제시문을 바탕으로 인성·가치관 관련 질문에 답하시오."],
    intention: "인성 및 가치관 평가",
    subjects: ["영어", "사회", "도덕"],
    keyConcepts: [],
    rubric: { high: "가치관이 분명하고 일관되며, 구체적 경험/사례와 연결", mid: "기본적인 입장은 있으나 깊이 부족", low: "추상적이거나 일관성 부족" },
    exampleCore: "자신의 경험과 제시문을 자연스럽게 연결하는 것이 중요",
    coachTip: "인성 문항은 '나'의 경험과 가치관을 제시문과 연결하세요.",
    selfCheck: ["제시문과 내 가치관을 연결했는가?", "구체적 경험이나 사례가 있는가?", "일관된 태도를 보여주었는가?"],
    vocab: []
  },
  {
    id: "2024-15",
    year: 2024,
    type: "OFFICIAL",
    track: "글로벌인재 / 학교생활우수자",
    department: "국제계열",
    card: "문항카드 15",
    title: "2024 논리적 사고력 (영문)",
    category: "논리적 사고력",
    prepMinutes: 1,
    answerMinutes: 2,
    topic: "2024학년도 논리적 사고력 영문 제시문",
    keyConflict: "PDF 부록 상세 추출 예정",
    passage: "※ 영문 제시문 전문은 PDF 부록 문항카드에서 추가 추출 후 업데이트됩니다.",
    questions: ["제시문을 읽고 논리적 사고력 관련 질문에 답하시오."],
    intention: "논리적 사고력 평가",
    subjects: ["영어", "사회"],
    keyConcepts: [],
    rubric: { high: "핵심 파악 + 대립 구조 이해 + 근거 있는 주장", mid: "기본 이해는 있으나 논리 전개가 약함", low: "핵심 파악 실패" },
    exampleCore: "대립 관점을 명확히 하고 자신의 선택을 정당화",
    coachTip: "생각하기 단계에서 한국어로 6단계를 먼저 완성하세요.",
    selfCheck: ["핵심 쟁점을 파악했는가?", "대립 관점을 언급했는가?", "근거와 사례가 있는가?"],
    vocab: []
  }
];

const PREDICTED = [
  {
    id: "2027-pred-1",
    year: 2027,
    type: "PREDICTED",
    title: "AI & Labor Market Polarization",
    topic: "Generative AI and job polarization",
    passage: "Predicted question based on recent trends. Not from official materials.\n\nGenerative AI is rapidly automating cognitive tasks previously thought to require human intelligence. While productivity gains are expected, concerns grow about polarization between high-skill workers who leverage AI and middle-skill workers whose roles may be displaced.",
    questions: ["What are the potential benefits and risks of generative AI for the labor market? Should governments intervene, and if so, how?"],
    coachTip: "This is a PREDICTED item for practice only."
  }
];

const VOCAB = [
  { word: "prosperity", meaning: "번영, 번성", pos: "n.", example: "Economic prosperity does not always equal happiness." },
  { word: "paradox", meaning: "역설, 모순", pos: "n.", example: "The prosperity paradox challenges conventional assumptions." },
  { word: "subjective well-being", meaning: "주관적 웰빙", pos: "n.", example: "Surveys measure subjective well-being." },
  { word: "stagnation", meaning: "정체", pos: "n.", example: "Happiness levels showed stagnation." },
  { word: "threshold", meaning: "임계점, 문턱", pos: "n.", example: "Beyond a certain income threshold..." },
  { word: "relative income", meaning: "상대 소득", pos: "n.", example: "Relative income affects satisfaction more than absolute income." },
  { word: "adaptation", meaning: "적응", pos: "n.", example: "People adapt quickly to higher living standards." },
  { word: "offset", meaning: "상쇄하다", pos: "v.", example: "The costs may offset the benefits." },
  { word: "sustainability", meaning: "지속가능성", pos: "n.", example: "Environmental sustainability should be considered." },
  { word: "social capital", meaning: "사회적 자본", pos: "n.", example: "Weakened community ties reduce social capital." },
  { word: "companion", meaning: "동반자", pos: "n.", example: "AI companion apps are popular among teens." },
  { word: "empathetic", meaning: "공감하는", pos: "adj.", example: "The AI can sound empathetic." },
  { word: "loneliness", meaning: "외로움", pos: "n.", example: "These apps may reduce loneliness." },
  { word: "dependency", meaning: "의존", pos: "n.", example: "Emotional dependency is a concern." },
  { word: "ambiguity", meaning: "모호함", pos: "n.", example: "Real relationships involve ambiguity." },
  { word: "regulation", meaning: "규제", pos: "n.", example: "Age-appropriate regulation is needed." },
  { word: "transparency", meaning: "투명성", pos: "n.", example: "Transparency about AI nature is important." },
  { word: "manipulation", meaning: "조작", pos: "n.", example: "Emotional manipulation techniques should be restricted." },
  { word: "stifle", meaning: "억누르다", pos: "v.", example: "Over-regulation could stifle innovation." },
  { word: "adolescent", meaning: "청소년", pos: "n./adj.", example: "Adolescents are still forming their identities." },
  { word: "polarization", meaning: "양극화", pos: "n.", example: "Job polarization is a growing concern." },
  { word: "leverage", meaning: "활용하다", pos: "v.", example: "High-skill workers can leverage AI tools." },
  { word: "displace", meaning: "대체하다", pos: "v.", example: "AI may displace certain middle-skill jobs." },
  { word: "well-being", meaning: "웰빙, 행복", pos: "n.", example: "Policy should focus on well-being indicators." },
  { word: "trade-off", meaning: "상충 관계", pos: "n.", example: "There is a trade-off between growth and equality." }
];
